const fs=require('fs'),vm=require('vm');
const ctx={console};
ctx.window={}; ctx.globalThis=ctx;
ctx.document={getElementById:()=>null,querySelectorAll:()=>[],querySelector:()=>null,createElement:()=>({style:{},dataset:{},setAttribute(){},appendChild(){}}),addEventListener:()=>{}};
ctx.localStorage={getItem:()=>null,setItem:()=>{}};
ctx.alert=()=>{}; ctx.navigator={clipboard:{writeText:()=>Promise.resolve()}};
vm.createContext(ctx);
let eng=fs.readFileSync(__dirname+'/.build/check_engine.js','utf8').replace(/load\(\);[\s\S]*$/,'');
vm.runInContext(fs.readFileSync(__dirname+'/.build/check_bank.js','utf8'),ctx);
vm.runInContext(eng,ctx);
vm.runInContext(fs.readFileSync(__dirname+'/tests.js','utf8'),ctx);
